### ISSUE TITLE
Instructions on how to install in readme

### ISSUE THREAD

**Issue by Duoquadragesimal** [theRealPadster/spurdle#8]
### 📝 Provide a description of the new feature

Could you put instructions on how to install this in the readme? Even if it's just cloning the repo I think that would be useful.

**Comment by theRealPadster** [comment]
This is a good point. It looks like the build folder is in the gitignore or something cause nothing is there. So as it stands, you'd have to download the repo, extract, `cd` into the folder, `yarn install`, `yarn build` and then use the build folder as a custom app. I'll have to look into sorting that out so there are downloads to use and you don't need to build. But it's heavily work-in-progress right now and not even remotely finished or fun. It just uses the currently playing song, so you know what it is already lol.

**Comment by theRealPadster** [comment]
@Duoquadragesimal
Added a branch with the built version on it. If you download the "dist" branch, you can put it into a new "spurdle" folder and copy it into your spicetify custom apps folder. Then add to your config and it should work. I'm gonna work on adding install instructions to the readme still.

**Comment by theRealPadster** [comment]
Readme updated!
